export const ACTIVATEBUFFERTOOL = 'ACTIVATEBUFFERTOOL'
export const CREATEBUFFERDATATRANSFER = 'CREATEBUFFERDATATRANSFER'
export const BUFFERDISTANCE  = 'BUFFERDISTANCE'
export const REMOVEBUFFER  = 'REMOVEBUFFER'