export const CADVIEWACTIVATE = 'CADVIEWACTIVATE'
export const SWITCHTOCADSVIEW = 'SWITCHTOCADSVIEW'
export const SEARCHBARCHANGED = 'SEARCHBARCHANGED'
export const CHANGEFILTERTYPE = 'CHANGEFILTERTYPE'