export const FILEVIEWACTIVATE = 'FILEVIEWACTIVATE'
export const SWITCHTOFILESVIEW = 'SWITCHTOFILESVIEW'
export const SEARCHBARCHANGED = 'SEARCHBARCHANGED'
export const CHANGEFILETYPE = 'CHANGEFILETYPE'